services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: roommate-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME} 
    ports:
      - '127.0.0.1:5432:5432' # do not expose LAN
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - roommate-network

  # NestJS Application (Development)
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    container_name: roommate-app-dev
    restart: unless-stopped
    ports:  
      - '127.0.0.1:3000:3000'
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
      APP_NAME: ${APP_NAME}
    volumes:
      - .:/app # Sync your code changes ||Â The container's /app is actually pointing to your local folder
      - /app/node_modules # keep container's node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - roommate-network
    command: npm run start:dev

volumes:
  postgres_data_dev:
    driver: local

networks:
  roommate-network:
    driver: bridge
